@extends('layouts.website_layout')
@section('title','Waste Management')
@section('page_content')
  <!-- ##### Breadcrumb Area Start ##### -->
  <div class="famie-breadcrumb">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Waste Management</li>
        </ol>
      </nav>
    </div>
  </div>
  <!-- ##### Breadcrumb Area End ##### -->

  <!-- ##### About Us Area Start ##### -->
  <section class="about-us-area">
    <div class="container">
      <div class="row align-items-center">

        <!-- About Us Thumbnail -->
        <div class="col-12 col-lg-6">
          <div class="about-us-thumbnail">
            <img src="{{asset('img/bg-img/24.jpg')}}" alt="">
          </div>
        </div>

        <!-- About Us Content -->
        <div class="col-12 col-lg-6">
          <div class="about-us-content content">
            <!-- Section Heading -->
            <div class="section-heading mb-15">
              <p>Campaigns</p>
              <h2><span>Waste</span> Management</h2>
              <img src="img/core-img/decor.png" alt="">
            </div>
            <p>Waste management is the activities and actions required to manage waste from its inception to its final disposal. This includes the collection, transport, treatment and disposal of waste, together with monitoring and regulation of the waste management process. Generally, waste is categorized within 5 categories: Liquid waste; Solid waste; Organic waste; Recyclable waste and Hazardous waste. We, have focused on the nearest and the possible waste that needs attention and can be looked into it.  Landfills are an increasingly pressing problem. Less and less land is available to deposit refuse, but the volume of waste is growing. As a result, segregating waste is not just of environmental importance, but also of economic concern.</p>
          </div>
        </div>
        <div class="col-12 col-lg-12">
          <div class="about-us-content content mb-100">
            <h4><strong>Objectives are as follows:</strong></h4>
            <ul>
              <li>Seeking to minimise environmental impact by proper segregation of waste (dry ad wet) ultimately minimising the load on dumping yards</li>
              <li>Promote 3Rs – Reduce, Reuse and Recycle.</li>
              <li>Building on existing resources and services</li>
              <li>To create, implement and demonstrate the impact and increased sustainability of waste collection methodologies</li>
              <li>Promoting public awareness through consultation and participation</li>
            </ul>
            <br/>
            <h4><strong>Waste Management is broadly divided in two categories</strong></h4>
            <p><strong>Wet waste management</strong></p>
            <p> Wet waste typically refers to organic waste usually generated by eating establishments and is heavy in weight due to dampness. This type of waste can be easily broken down and eliminated at its inception itself. Different measures for managing the wet waste are through Decomposting; Biogas; Vermicomposting and Briquetting.</p>

            <p class="ml-30"><strong>Wet waste management and Household level</strong></p>
            <p class="ml-30">The team guides and helps the individuals to segregate the wet and dry waste at the inception level and promotes to decompose the wet waste collected at the house level. This can be done through available decomposing units for household (which can be provided by the team) and also provide guidance for DIY composting at home. The residual of the decomposed can be used as fertilizers and the moisture drained down as a liquid can be used as pesticide for the plants. We also offer simple ways to manage the household wet waste for a single flat up to apartment level. We have introduced “Magic Bucket” (courtesy of Paryavaran Dakshata Mancha) to the audience with a ready prototype and explained the procedure to manage daily wet waste through it.</p>
            <p class="ml-30"><strong>Wet waste at society level</strong></p>
            <p class="ml-30">Alike the wet waste process at household we provide information about the processes available for eliminating waste at society level. This is also covered at the seminars taken by the team. The team not only provides information but also helps in implementation of large composting units for the societies. Introduce two separate disposal drums on your complex ground, and explain to people the importance of this segregation. We also try to connect to like-minded organisations which are solely dedicated to waste management in apartment complex. Different types of composting at society level are: Pit Composting; Concrete compost pits; vermi-compost etc.</p>

            <p><strong>Dry waste Management</strong></p>
            <p>To influence residents through “Swachha Dombivli Abhiyan” we have conducted seminars that provide easy solutions for segregation of different types of household waste and its proper management. Through the seminars, the audiences were made realized about the seriousness of the current predicament in our city and the following repercussions that might occur if not dealt with. We have defined the dry and wet waste in simple words so that people could easily understand and able to recognize the differences between them.</p>
            <p>Till date we have visited 25 residential societies, social community groups, schools and colleges across the city and gave seminar to approximately 3500 people.</p>
            <p>A key step towards dry waste manage id forming a chain of Scrap collector/ recyclers (Bhangarwala). While identifying the solutions for the increasing waste management problem, the team realized that the important and nearest person who can help in this mission is the nearest bhangarwala.  These are the people who collect each and every scrap from each and every house whether it be old cloths, electronic items or plastics. The team has connected all the bhangarwala and unified them in this mission by helping them to understand the different avenues available for recycling, refurbishing and also tying them up with specific companies, providing a win-win solution for the bhangarwala and the society.  For eg: helping the bhangarwala understand the importance of plastic recycling; tying them with the plastic recyclers nearby, which will promote them to collect plastic from the public ultimately promoting proper management of plastics through household.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ##### About Us Area End ##### -->

  <!-- ##### FAQ Area Start ##### -->
  <section class="famie-faq-area">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- Section Heading -->
          <div class="section-heading text-center">
            <p>HAVE A QUESTION?</p>
            <h2><span>Get answers</span> to FAQs about waste management</h2>
            <img src="img/core-img/decor2.png" alt="">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="accordions" id="accordion" role="tablist" aria-multiselectable="true">

            <!-- Single Accordian Area -->
            <div class="panel single-accordion">
              <h6><a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Are organic products of the same quality as other food and drink ?
                  <span class="accor-open"><i class="arrow_carrot-up" aria-hidden="true"></i></span>
                  <span class="accor-close"><i class="arrow_carrot-down" aria-hidden="true"></i></span>
                </a></h6>
              <div id="collapseOne" class="accordion-content collapse show">
                <p>Organic production methods differ from conventional ones – but the aim is nonetheless to produce top-quality food and drink. Organic produce has to meet the same safety standards as other foods and complies with EU General Food
                  law. The difference is that instead of using chemical compounds to combat pests or weeds, organic farmers use multi-annual crop rotations and resistant varieties to prevent such problems from occurring in the first place.</p>
              </div>
            </div>

            <!-- Single Accordian Area -->
            <div class="panel single-accordion">
              <h6>
                <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo" data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">Do organic products taste different from other food and drink ?
                  <span class="accor-open"><i class="arrow_carrot-up" aria-hidden="true"></i></span>
                  <span class="accor-close"><i class="arrow_carrot-down" aria-hidden="true"></i></span>
                </a>
              </h6>
              <div id="collapseTwo" class="accordion-content collapse">
                <p>Organic production methods differ from conventional ones – but the aim is nonetheless to produce top-quality food and drink. Organic produce has to meet the same safety standards as other foods and complies with EU General Food
                  law. The difference is that instead of using chemical compounds to combat pests or weeds, organic farmers use multi-annual crop rotations and resistant varieties to prevent such problems from occurring in the first place.</p>
              </div>
            </div>

            <!-- Single Accordian Area -->
            <div class="panel single-accordion">
              <h6>
                <a role="button" aria-expanded="true" aria-controls="collapseThree" class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapseThree">Are all of your poultry, meat and fish products raised humanely ?
                  <span class="accor-open"><i class="arrow_carrot-up" aria-hidden="true"></i></span>
                  <span class="accor-close"><i class="arrow_carrot-down" aria-hidden="true"></i></span>
                </a>
              </h6>
              <div id="collapseThree" class="accordion-content collapse">
                <p>Organic production methods differ from conventional ones – but the aim is nonetheless to produce top-quality food and drink. Organic produce has to meet the same safety standards as other foods and complies with EU General Food
                  law. The difference is that instead of using chemical compounds to combat pests or weeds, organic farmers use multi-annual crop rotations and resistant varieties to prevent such problems from occurring in the first place.</p>
              </div>
            </div>

            <!-- Single Accordian Area -->
            <div class="panel single-accordion">
              <h6>
                <a role="button" aria-expanded="true" aria-controls="collapseFour" class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapseFour">Does FAMIE contain any ingredients from China or outside of North America ?
                  <span class="accor-open"><i class="arrow_carrot-up" aria-hidden="true"></i></span>
                  <span class="accor-close"><i class="arrow_carrot-down" aria-hidden="true"></i></span>
                </a>
              </h6>
              <div id="collapseFour" class="accordion-content collapse">
                <p>Organic production methods differ from conventional ones – but the aim is nonetheless to produce top-quality food and drink. Organic produce has to meet the same safety standards as other foods and complies with EU General Food
                  law. The difference is that instead of using chemical compounds to combat pests or weeds, organic farmers use multi-annual crop rotations and resistant varieties to prevent such problems from occurring in the first place.</p>
              </div>
            </div>

            <!-- Single Accordian Area -->
            <div class="panel single-accordion">
              <h6>
                <a role="button" aria-expanded="true" aria-controls="collapseFive" class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapseFive">Are you a retailer interested in bringing in FARMIE products ?
                  <span class="accor-open"><i class="arrow_carrot-up" aria-hidden="true"></i></span>
                  <span class="accor-close"><i class="arrow_carrot-down" aria-hidden="true"></i></span>
                </a>
              </h6>
              <div id="collapseFive" class="accordion-content collapse">
                <p>Organic production methods differ from conventional ones – but the aim is nonetheless to produce top-quality food and drink. Organic produce has to meet the same safety standards as other foods and complies with EU General Food
                  law. The difference is that instead of using chemical compounds to combat pests or weeds, organic farmers use multi-annual crop rotations and resistant varieties to prevent such problems from occurring in the first place.</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ##### FAQ Area End ##### -->
@endsection